travis:
  secure:
    BINSTAR_TOKEN: f7tM+tJQkcZUlxu4RdVNQPHo1jN7EAd3FRXP073nQnEAMVsTmSIdoqUiDtrEU2sy+bVKS7MlRGj7LxxGkcnSjaNBgK7Jp0WFes7GWdU+ERhybqI4+PXQy80nmGL8iJmLMDU+MtlooJDjvmlAu5uVyd9BbyB2QI1a8bjvcqMsBksWA6Rkbmp41ZH9zgcHikVzTo0lqQhHaqfz/hUlVoxDxHjeLVBtElH3KL0P8Gt3gScSul1k/ridWSuc/Am/pZiwBlswDcnQGPjfvMpMYgczxN38/+0IaJwl1cIUjIDtRouQIGZ7HAiWcz/eoTnXolEWoiiA/+emrw+ftVrZJiKYsWq568FPZhchRPjEN4+kSiZal8G4uYBTXo4Tj30gv768l9KVCyzxPJw0ql82l7oBYRvuvDpAdi2gpiqntzY/hcimtSoUXRbqMp6lTkf2N0UTl/SATQXlgRNumXocWZiUQ2Ax3TIKwggi8KhEUu63CIUF41aEDnhztyTeArMHqTNmnOCE1sWEOUHbxYFU7eljr5KNdTCsmGY/Yuq16EGAwBZPWS/gVoIhFkEprEEUdDZMi9TWDdMyuJUd763ij0LG4MMjSOoDR7CfUFRUOZViSuTigoY1sEOy90Y6bK4+UNfHRPp4CHI+OHzjIoiOFM2sfAsVGZNmvFRB7+Zeft7kPKc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
