travis:
  secure:
    BINSTAR_TOKEN: HE5AhBFCEhBdnpXQg/UU/4+dQ2Dh0wAtX2naGKIU9sogf5K2thHMaqOMX2IDUAKPE6KfrJMeffzTOzHvEcsMXvyLsNu4VpbE1C8EYxq7eYjVaayYizNy56ojr0BsXzP4WZ4q59bE1wLdUFL4B/Q4qXRKpqm2uiG/TZkKB+doIReRYB4C4hAsytM+POQIEs8Zdj7Rm7Ad4cdz0QTq3+UanAjaLUJTCyDeGc121hPhxX0XeSRlCSW4JxRt54RvEQOavwWPWuo9gOo8VroJOVlmNIektjozM7jkshUwnWWTO0/a6NC0xTuB5rR9H2vUJO49NNz1Y3JKwe4GZF9tm/wC4ZxUQ/HjV1DpBTCCSQAuhgGACnNRkXA+LioKarLDFx4KwjtzEy5AUD7gKbAfMWHat8fWvregpepuXR/+xZerjJ7pbZJ9DwHFOqu2ENscE7paeqOqu1VTfGEaE9mQQXgRwnuH32BVyYm5ES187DILXP0P/CO+wS8QK5jaIs58/FUrD4MSwJVlb13Ie2uajZvGdQhnUrBzT6erCb2TpntS0aqq6zygcyqY2gN/2+T0GDW4pslSfCiMA929EyNDbv4bJy/Xa9AUhfK/AcRKjBXlBwLhvT7+QF6Zk9C5sOGpAfNHA3sQjruTWjjFA5HBRqFO6ylnUiEDrcCGeLPlPXZJi84=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
